require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'



platform :ios, '10.0'

target 'Stromboard' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])


  pod 'rn-fetch-blob',
    :path => '../node_modules/rn-fetch-blob'

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"


  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  target 'StromboardTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'Stromboard-tvOS' do
  # Pods for Stromboard-tvOS

  target 'Stromboard-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
